spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      s3:
        credentials:
          accessKey: ${AWS_S3_ACCESSKEY}
          secretKey: ${AWS_S3_SECRETKEY}
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

jwt:
  secret: ${JWT_SECRETS}
  expiration_time:
    access_token: 30000000000000000 # 5분
    refresh_token: 86400000000000000 # 일주일

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    prod-redirect-uri: ${KAKAO_PROD_REDIRECT_URI}
    dev-redirect-uri: ${KAKAO_DEV_REDIRECT_URI}
    local-redirect-uri: ${KAKAO_LOCAL_REDIRECT_URI}
    auth-uri: https://kauth.kakao.com
    api-uri: https://kapi.kakao.com

server:
  servlet:
    session:
      cookie:
        domain: ${COOKIE_DOMAIN}

saramin:
  api:
    base-url: https://oapi.saramin.co.kr
    access-key: ${SARAMIN_SECRET_KEY}

ai:
  api:
    base-url: https://dev-ai.careerbee.co.kr

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus  # 노출할 엔드포인트 지정
  endpoint:
    health:
      show-details: always  # 상세 정보 포함
  server:
    port: 8080
