spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRETS}
  expiration_time:
    access_token: 300000 # 5분
    refresh_token: 604800000 # 일주일

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    auth-uri: https://kauth.kakao.com
    api-uri: https://kapi.kakao.com

server:
  servlet:
    session:
      cookie:
        domain: ${COOKIE_DOMAIN}

sentry:
  dsn: ${SENTRY_DSN}  # 필수: Sentry DSN을 환경변수로 주입
  environment: prod     # 선택: dev, prod 등 환경 구분
  traces-sample-rate: 1.0 # 성능 트랜잭션 수집 비율 (1.0 = 100%)
  attach-stacktrace: true # 예외가 발생하지 않아도 스택트레이스를 첨부
  send-default-pii: true  # 유저정보 등 개인 식별 정보 포함 여부
  enable-tracing: true    # 성능 트랜잭션 수집 여부
  debug: false            # 로컬에서 테스트 시 true로 하면 Sentry 로그 출력
  logging:
    minimum-event-level: info         # Sentry에 보낼 최소 로그 수준 (e.g., error, warning, info)
    minimum-breadcrumb-level: info    # Breadcrumbs 수집 로그 수준