spring:
  datasource:
    url: jdbc:mysql://localhost:3306/careerbee_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mumu
    password: mumu
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: asdjfkajsdlfkjlkadjlfkasjdefwerasdfkjasdlkfjasdlkjflkwjeflkjsadlfasdfewdf
  expiration_time:
    access_token: 30000000000000000 # 5분
    refresh_token: 86400000000000000 # 일주일

oauth:
  kakao:
    client-id: 1342353523423
    prod-redirect-uri: https://test.co.kr
    dev-redirect-uri: https://test.co.kr
    local-redirect-uri: https://test.co.kr
    auth-uri: https://kauth.kakao.com
    api-uri: https://kapi.kakao.com

server:
  servlet:
    session:
      cookie:
        domain: https://test.co.kr
