spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRETS}
  expiration_time:
    access_token: 30000000000000000 # 5분
    refresh_token: 86400000000000000 # 일주일

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    prod-redirect-uri: ${KAKAO_PROD_REDIRECT_URI}
    dev-redirect-uri: ${KAKAO_DEV_REDIRECT_URI}
    local-redirect-uri: ${KAKAO_LOCAL_REDIRECT_URI}
    auth-uri: https://kauth.kakao.com
    api-uri: https://kapi.kakao.com

server:
  servlet:
    session:
      cookie:
        domain: ${COOKIE_DOMAIN}
